{{- if .Values.operator.basicAuthSecret.create }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.operator.basicAuthSecret.SecretName }}
type: Opaque
data:
    {{ .Values.operator.basicAuthSecret.UsernameKey }}: {{ printf "admin" | b64enc }}
    {{ .Values.operator.basicAuthSecret.PasswordKey }}: {{ printf "admin" | b64enc }}
{{- end }}
